#!/bin/bash

# Update the system packages
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Configure Nginx to listen on port 80
sed -i 's/^\(\s*listen\s*\)80\s*;/\180;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create an HTML file with the content "Hello World!"
echo "Hello World!" > /var/www/html/index.html
